version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: o-labs-service
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=db
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
      - SLACK_BOT_TOKEN=$SLACK_BOT_TOKEN
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/o-labs
      - node_modules:/usr/src/o-labs/node_modules
      - ./dist:/usr/src/o-labs/dist
    networks:
      - o-labs-network
    depends_on:
      - mongo
    # command: ["./wait-for-it.sh", "db:27017", "--", "/usr/src/o-labs/node_modules/.bin/npm","start"]
    command: ["bash","./wait-for-it.sh", "db:27017", "--", "npm", "start"]

  mongo:
    image: mongo:4.1.8-xenial
    container_name: db
    # command: "--auth"
    restart: unless-stopped
    env_file: .env
    ports:
        - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - dbdata:/data/db
    networks:
      - o-labs-network

networks:
  o-labs-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:
